title: "Yating Lin"
author: "Yating Lin"
description: "My Homepage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true              # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {file: "README_about.md", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:yatinlin@umich.edu"}
  - {title: Github, icon: github, url: "https://github.com/Yating05"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?hl=en&user=Ubfl6NUAAAAJ&sortby=pubdate&view_op=list_works&gmla=AH8HC4wUMQl75XcMaITbZdHmfaAjxT6zTD6CQ_Vrek6sBI0sMVv771Wo2WEsIBiPMfR-sgz_I9o5xguyF4OrIrO94ECqKEKHJRh_0A"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
